#!/bin/bash

project_changes() {
  directory=$1
  git diff HEAD --name-only --cached | grep "^$directory/.*"
}

lint_packages() {
  if project_changes "packages" > /dev/null 2>&1; then
    repo_root="$(git rev-parse --show-toplevel)"
    cd "$repo_root"
    if ! pnpm run lint; then
      echo -e "\033[1m\033[31mLinting failed, please fix the reported issues\033[0m\n"
      exit 1
    fi
    if ! pnpm run format:check; then
      echo -e "\033[1m\033[31mFormatting check failed, please run 'pnpm run format'\033[0m\n"
      exit 1
    fi
    echo -e "\033[1m\033[32mLinting and formatting passed!\033[0m\n"
  else
    echo -e "\033[1m\033[34mNo changes to packages, skipping lint\033[0m\n"
  fi
}

lint_packages
