import { readFileSync } from "node:fs";
import { join } from "node:path";

export type ResourceLink = {
  type: string;
  configKey: string;
};

export type ResourceLinks = ReadonlyMap<string, ResourceLink>;

/**
 * Well-known config namespace name for resource identifiers.
 * The build/deploy process populates this namespace with actual infrastructure
 * identifiers (bucket names, queue URLs, etc.).
 */
export const RESOURCE_CONFIG_NAMESPACE = "resources";

/**
 * Filename the Celerity CLI writes into the handler bundle at build time.
 * The SDK loads it on cold start to discover the resource topology without
 * needing the payload to travel through environment variables.
 */
export const RESOURCE_LINKS_FILENAME = "__celerity_resource_links__.json";

/**
 * Resolves the path the resource links file should be read from. The file
 * sits next to the handler entry point by default; runtime platforms (e.g.
 * local dev) may set `CELERITY_RESOURCE_LINKS_PATH` to point the SDK at a
 * different location.
 */
function resolveResourceLinksPath(): string {
  const override = process.env.CELERITY_RESOURCE_LINKS_PATH;
  if (override) return override;
  return join(process.cwd(), RESOURCE_LINKS_FILENAME);
}

/**
 * Loads the resource link topology produced at build time by the Celerity CLI.
 * Returns a map of resource name → { type, configKey }. Actual infrastructure
 * identifiers are resolved via ConfigService at runtime, not from this file.
 *
 * Throws if the file is missing or malformed — the file is a required build
 * artifact, not an optional input.
 */
export function captureResourceLinks(): ResourceLinks {
  const path = resolveResourceLinksPath();
  let raw: string;
  try {
    raw = readFileSync(path, "utf8");
  } catch (err) {
    const cause = err instanceof Error ? err.message : String(err);
    throw new Error(
      `resource links file not found at ${path}: ${cause}. ` +
        "this file is generated by `celerity build` / `celerity dev`.",
    );
  }

  let parsed: Record<string, { type: string; configKey: string }>;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    const cause = err instanceof Error ? err.message : String(err);
    throw new Error(`resource links file at ${path} is not valid JSON: ${cause}`);
  }

  return new Map(Object.entries(parsed).map(([resourceName, link]) => [resourceName, link]));
}

/** Filters resource links by type, returning resourceName → configKey. */
export function getLinksOfType(links: ResourceLinks, type: string): Map<string, string> {
  const result = new Map<string, string>();
  for (const [resourceName, link] of links) {
    if (link.type === type) result.set(resourceName, link.configKey);
  }
  return result;
}

/** Returns the set of distinct resource types present in the links. */
export function getResourceTypes(links: ResourceLinks): Set<string> {
  return new Set([...links.values()].map((l) => l.type));
}
